### ISSUE TITLE
Detective doesn't behave well when partition numbers on test and reference sides differ

### ISSUE THREAD

**Issue by farmdawgnation** [farmdawgnation/kafka-detective#7]
We generate various exceptions when Detective is using differently numbered partitions in the reference and test size. We should update the integration tests to trigger this condition and play smash the bug to get this functionality working.

**Comment by thomas-holmes** [comment]
Reference side:
```
17:11:26.604 [binlogs_mailchimp_us7-99-consuming-thread] DEBUG c.m.k.d.CallbackKafkaConsumer - Consuming thread for binlogs_mailchimp_us7-99 is starting
17:11:26.610 [binlogs_mailchimp_us7-99-consuming-thread] ERROR c.m.k.d.CallbackKafkaConsumer - An unexpected exception occured during message consumption for binlogs_mailchimp_us7-99. Consumer will shut down.
java.lang.RuntimeException: Cannot find partition counter for partition 99 in this consumer.
	at com.mailchimp.kafka.detective.CallbackKafkaConsumer.$anonfun$getPositionAheadOfStartByPartition$1(CallbackKafkaConsumer.scala:113)
	at scala.Option.getOrElse(Option.scala:121)
	at com.mailchimp.kafka.detective.CallbackKafkaConsumer.getPositionAheadOfStartByPartition(CallbackKafkaConsumer.scala:113)
	at com.mailchimp.kafka.detective.monitor.MonitorWorker.$anonfun$shouldReferenceConsumerBackpressure$1(MonitorWorker.scala:146)
	at scala.runtime.java8.JFunction1$mcJI$sp.apply(JFunction1$mcJI$sp.java:12)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.mailchimp.kafka.detective.monitor.MonitorWorker.shouldReferenceConsumerBackpressure(MonitorWorker.scala:145)
	at com.mailchimp.kafka.detective.monitor.MonitorWorker.$anonfun$referenceConsumer$1(MonitorWorker.scala:175)
	at com.mailchimp.kafka.detective.CallbackKafkaConsumer.$anonfun$isBackpressuring$1(CallbackKafkaConsumer.scala:130)
	at com.mailchimp.kafka.detective.CallbackKafkaConsumer.$anonfun$isBackpressuring$1$adapted(CallbackKafkaConsumer.scala:130)
	at scala.Option.map(Option.scala:146)
	at com.mailchimp.kafka.detective.CallbackKafkaConsumer.isBackpressuring(CallbackKafkaConsumer.scala:130)
	at com.mailchimp.kafka.detective.CallbackKafkaConsumer$$anon$1.run(CallbackKafkaConsumer.scala:219)
```

Test side:
```
17:11:26.677 [binlogs_mailchimp_us7_stage-0-consuming-thread] DEBUG c.m.k.d.CallbackKafkaConsumer - Consuming thread for binlogs_mailchimp_us7_stage-0 is starting
17:11:26.687 [main] INFO  com.mailchimp.kafka.detective.Main$ - Monitor wardens started.
17:11:26.858 [pfs_us7-worker-0-comparison-thread-0] ERROR c.m.k.d.monitor.MonitorWorker - An exception occured during message handling
java.lang.RuntimeException: Cannot find partition counter for partition 0 in this consumer.
	at com.mailchimp.kafka.detective.CallbackKafkaConsumer.$anonfun$getPositionAheadOfStartByPartition$1(CallbackKafkaConsumer.scala:113)
	at scala.Option.getOrElse(Option.scala:121)
	at com.mailchimp.kafka.detective.CallbackKafkaConsumer.getPositionAheadOfStartByPartition(CallbackKafkaConsumer.scala:113)
	at com.mailchimp.kafka.detective.WindowingKafkaConsumer.getPositionAheadOfStartByPartition(WindowingKafkaConsumer.scala:46)
	at com.mailchimp.kafka.detective.monitor.MonitorWorker.testSubjectAfterFirstReferenceMessage$1(MonitorWorker.scala:207)
	at com.mailchimp.kafka.detective.monitor.MonitorWorker.handleMessage(MonitorWorker.scala:218)
	at com.mailchimp.kafka.detective.monitor.MonitorWorker.$anonfun$start$3(MonitorWorker.scala:309)
	at com.mailchimp.kafka.detective.monitor.KeyAwareExecutor.$anonfun$submit$1(KeyAwareExecutor.scala:77)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
